<div class="row padding-1 p-1">
    <div class="col-md-12">
        
        {{-- id_estante is auto-generated by the database and should not be editable --}}
        <div class="form-group mb-2 mb20">
            <label for="id_almacen" class="form-label">{{ __('Almacen') }}</label>
            <select name="id_almacen" id="id_almacen" class="form-control @error('id_almacen') is-invalid @enderror">
                <option value="">{{ __('-- Select --') }}</option>
                @foreach(($almacenes ?? []) as $almId => $almName)
                    <option value="{{ $almId }}" {{ (string) old('id_almacen', $estante?->id_almacen) === (string) $almId ? 'selected' : '' }}>{{ $almName }}</option>
                @endforeach
            </select>
            {!! $errors->first('id_almacen', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="codigo_estante" class="form-label">{{ __('Codigo Estante') }}</label>
            <input type="text" name="codigo_estante" class="form-control @error('codigo_estante') is-invalid @enderror" value="{{ old('codigo_estante', $estante?->codigo_estante) }}" id="codigo_estante" placeholder="Codigo Estante">
            {!! $errors->first('codigo_estante', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="descripcion" class="form-label">{{ __('Descripcion') }}</label>
            <input type="text" name="descripcion" class="form-control @error('descripcion') is-invalid @enderror" value="{{ old('descripcion', $estante?->descripcion) }}" id="descripcion" placeholder="Descripcion">
            {!! $errors->first('descripcion', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>

    </div>
    <div class="col-md-12 mt20 mt-2">
        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
    </div>
</div>