<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CampanaRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            // id_campana is auto-generated by the DB. Validate payload fields instead.
            'nombre' => 'required|string|max:255',
            'descripcion' => 'nullable|string',
            'fecha_inicio' => 'nullable|date',
            'fecha_fin' => 'nullable|date',
            'imagen_banner' => 'nullable|string|max:255',
        ];
    }
}
