<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EstanteRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            // id_estante is auto-generated by the DB. Validate the payload fields instead.
            'id_almacen' => 'required|exists:almacenes,id_almacen',
            'codigo_estante' => 'required|string|max:255',
            'descripcion' => 'nullable|string|max:255',
        ];
    }
}
