<div class="row padding-1 p-1">
    <div class="col-md-12">
        
        {{-- id_espacio is auto-generated by the database and should not be editable --}}
        <div class="form-group mb-2 mb20">
            <label for="id_estante" class="form-label">{{ __('Id Estante') }}</label>
            <input type="text" name="id_estante" class="form-control @error('id_estante') is-invalid @enderror" value="{{ old('id_estante', $espacio?->id_estante) }}" id="id_estante" placeholder="Id Estante">
            {!! $errors->first('id_estante', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        <div class="form-group mb-2 mb20">
            <label for="codigo_espacio" class="form-label">{{ __('Codigo Espacio') }}</label>
            <input type="text" name="codigo_espacio" class="form-control @error('codigo_espacio') is-invalid @enderror" value="{{ old('codigo_espacio', $espacio?->codigo_espacio) }}" id="codigo_espacio" placeholder="Codigo Espacio">
            {!! $errors->first('codigo_espacio', '<div class="invalid-feedback" role="alert"><strong>:message</strong></div>') !!}
        </div>
        {{-- capacidad and unidad_medida were removed from the schema and are not editable --}}

    </div>
    <div class="col-md-12 mt20 mt-2">
        <button type="submit" class="btn btn-primary">{{ __('Submit') }}</button>
    </div>
</div>